// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmA0fp2TIUOjyGWHvHvGoo0u8wiKQxqN0',
    appId: '1:45294145587:web:2f50e07c2c8766994d9346',
    messagingSenderId: '45294145587',
    projectId: 'gdgnativechatapp',
    authDomain: 'gdgnativechatapp.firebaseapp.com',
    storageBucket: 'gdgnativechatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHrlRPz_PSJYm760tM8-h7KlK7tQFTs0Y',
    appId: '1:45294145587:android:e6cf7c412a0241f84d9346',
    messagingSenderId: '45294145587',
    projectId: 'gdgnativechatapp',
    storageBucket: 'gdgnativechatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufYLY5H4tuqUZpKc39h7UdZaOqdO4k_E',
    appId: '1:45294145587:ios:0fb26767d564e6554d9346',
    messagingSenderId: '45294145587',
    projectId: 'gdgnativechatapp',
    storageBucket: 'gdgnativechatapp.firebasestorage.app',
    iosBundleId: 'com.example.gdgNativechatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBufYLY5H4tuqUZpKc39h7UdZaOqdO4k_E',
    appId: '1:45294145587:ios:0fb26767d564e6554d9346',
    messagingSenderId: '45294145587',
    projectId: 'gdgnativechatapp',
    storageBucket: 'gdgnativechatapp.firebasestorage.app',
    iosBundleId: 'com.example.gdgNativechatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmA0fp2TIUOjyGWHvHvGoo0u8wiKQxqN0',
    appId: '1:45294145587:web:2d698dcb80ba480a4d9346',
    messagingSenderId: '45294145587',
    projectId: 'gdgnativechatapp',
    authDomain: 'gdgnativechatapp.firebaseapp.com',
    storageBucket: 'gdgnativechatapp.firebasestorage.app',
  );
}
